import Head from 'next/head';
import Link from 'next/link';
import type { NextPage } from 'next';

const Home: NextPage = () => {
    return (
        <div className="font-sans">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Link href="/barnsley">Barnsley fern</Link>
            </main>
            <footer>
                <a
                    href="https://github.com/mmmalik"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Github
                </a>
            </footer>
        </div>
    );
};

export default Home;
