name: deploy

on:
    push:
        branches: main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.1.0
              with:
                  version: 6

            - name: Install dependencies
              run: pnpm i

            - name: Build page
              run: pnpm build && pnpm export

            - name: Deploy to GitHub Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  target_branch: gh-pages
                  build_dir: out
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
